# Generated by Django 3.1.2 on 2020-10-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('publish_date', models.DateField()),
                ('isbn', models.IntegerField()),
                ('pages_number', models.PositiveIntegerField()),
                ('cover_link', models.TextField()),
                ('language', models.TextField()),
            ],
        ),
    ]
